import SiteLogo from "@/components/landing/logo";
import DynamicBackground from "@/components/ui/background";
import { ThemeProvider } from "@/components/ui/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<DynamicBackground
						imageName="Main Background"
						defaultUrl="/tron-image-2.png"
						className="bg-background bg-cover justify-center flex h-full min-h-dvh w-full flex-col items-center bg-fixed"
						overlay={true}
						overlayOpacity={20}
					>
						<SiteLogo />
						{children}
					</DynamicBackground>
				</ThemeProvider>
			</body>
		</html>
	);
}
